package constants

const (
	Chicken   = "CHICKEN"
	Beef      = "BEEF"
	Seafood   = "SEAFOOD"
	Vegetable = "VEGETABLE"
	Dessert   = "DESSERT"
	One = "1."
	Two = "2."
	Three = "3."
	Four = "4."
	Five = "5."
	Six = "6."
	Seven = "7."
	Eight = "8."
	Nine = "10."
	About = "ABOUT RECIPE BOX"
	Exit = "EXIT RECIPE BOX"
	Incorrect = "Incorrect Input, please try again"
	PickDifferentIng = "PICK DIFFERENT MAIN INGREDIENT"
	DownloadRecipe = "DOWNLOAD RECIPE"
	ChooseDifferentRec = "CHOOSE A DIFFERENT RECIPE"
	UserInputReq = "(Type number and press enter to make your selection.)"
	ExitingRecipeBox = "*** EXITING RECIPE BOX ***"
)
